#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!\n" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo service nginx restart
 