#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
sudo echo "Hello World!\n" > /var/www/html/index.nginx-debian.html
sudo service nginx start
service nginx restart
