#!/usr/bin/env bash
# baah script Creates file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"
trap 'echo "Y U no love me?!"' SIGINT
trap "sudo rm -f /var/run/holbertonscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/holbertonscript.pid; echo I hate the kill command; exit" SIGTERM

while :
do
	echo "To infinity and beyond"
	sleep 2

done
